import { ShipConfig, UpgradeCard } from './types';

export const SHIPS: ShipConfig[] = [
  {
    id: 'vanguard',
    name: 'Vanguard Alpha',
    title: 'Tactical Interceptor',
    description: 'Balanced combat fighter with twin plasma blasters and emergency Phase Dash.',
    speed: 340,
    maxHp: 100,
    maxShield: 100,
    shieldRegen: 8,
    fireRate: 6.5,
    bulletDamage: 22,
    specialAbility: 'Phase Dash (Invulnerable Blink)',
    specialCooldown: 4000,
    color: '#06b6d4', // cyan-500
    secondaryColor: '#3b82f6',
  },
  {
    id: 'spectre',
    name: 'Phantom Spectre',
    title: 'High-Velocity Stealth Striker',
    description: 'Ultra-agile hunter with high critical chance and EMP Shockwave burst.',
    speed: 430,
    maxHp: 75,
    maxShield: 70,
    shieldRegen: 12,
    fireRate: 9.0,
    bulletDamage: 17,
    specialAbility: 'EMP Shockwave (Clears Projectiles)',
    specialCooldown: 5000,
    color: '#a855f7', // purple-500
    secondaryColor: '#ec4899',
  },
  {
    id: 'dreadnought',
    name: 'Nova Juggernaut',
    title: 'Armored Heavy Cruiser',
    description: 'Formidable fortress armed with dual cannons, reinforced armor, and auto-flak turrets.',
    speed: 260,
    maxHp: 180,
    maxShield: 150,
    shieldRegen: 6,
    fireRate: 4.8,
    bulletDamage: 38,
    specialAbility: 'Overdrive Shield Barrier',
    specialCooldown: 7000,
    color: '#f59e0b', // amber-500
    secondaryColor: '#ef4444',
  },
  {
    id: 'chrono',
    name: 'Solaris Chrono',
    title: 'Temporal Singularity Vessel',
    description: 'Harnesses tachyon fields to slow incoming threats and discharge chain lightning.',
    speed: 310,
    maxHp: 90,
    maxShield: 90,
    shieldRegen: 10,
    fireRate: 5.5,
    bulletDamage: 28,
    specialAbility: 'Chrono Stasis (Time Dilation)',
    specialCooldown: 6000,
    color: '#10b981', // emerald-500
    secondaryColor: '#06b6d4',
  },
];

export const UPGRADES_LIST: Omit<UpgradeCard, 'level'>[] = [
  {
    id: 'plasma_scatter',
    name: 'Plasma Multi-Spread',
    description: 'Adds +1 simultaneous energy projectile to each weapon discharge.',
    icon: 'Sparkles',
    maxLevel: 4,
    rarity: 'rare',
  },
  {
    id: 'hyper_velocity',
    name: 'High-Velocity Accelerator',
    description: 'Increases projectile speed by +25% and damage by +18%.',
    icon: 'Zap',
    maxLevel: 5,
    rarity: 'common',
  },
  {
    id: 'tesla_coil',
    name: 'Arc Lightning Coil',
    description: 'Direct hits discharge electrical arcs that chain to up to 3 nearby enemies.',
    icon: 'Radio',
    maxLevel: 3,
    rarity: 'epic',
  },
  {
    id: 'kinetic_barrier',
    name: 'Aegis Shield Matrix',
    description: 'Expands maximum shield capacity by +30 and speeds up recharge rate by +25%.',
    icon: 'Shield',
    maxLevel: 4,
    rarity: 'common',
  },
  {
    id: 'orbital_drone',
    name: 'Orbital Sentinel Drone',
    description: 'Deploys an autonomous companion satellite that intercepts bullets and fires lasers.',
    icon: 'Cpu',
    maxLevel: 3,
    rarity: 'epic',
  },
  {
    id: 'magnet_siphon',
    name: 'Quantum Magnetar Siphon',
    description: 'Amplifies resource pull radius by +75% and grants bonus XP per shard.',
    icon: 'Compass',
    maxLevel: 3,
    rarity: 'common',
  },
  {
    id: 'nanite_hull',
    name: 'Nanite Hull Repair',
    description: 'Instantly repairs 35 HP and grants passive hull regeneration (+1.5 HP/s).',
    icon: 'Heart',
    maxLevel: 3,
    rarity: 'rare',
  },
  {
    id: 'crit_matrix',
    name: 'Thermal Overcharge Core',
    description: 'Adds +20% Critical Strike Chance causing 2.5x devastating damage.',
    icon: 'Flame',
    maxLevel: 4,
    rarity: 'rare',
  },
];
